name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    name: Foundry project
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.8.1

      - name: Show Forge version
        run: |
          forge --version

      - name: Check Forge formatting
        run: make format-check
        id: fmt

      - name: Lint with warnings denied
        run: make lint
        id: lint

      - name: Build with warnings denied
        run: make build-check
        id: build

      - name: Run full Forge test suite
        run: make test
        id: test
